version: '3'

networks:
  internal:
    external: false

services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.11.3
    mem_limit: 512m
    networks:
      - internal
    cpus: '0.4'
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./data/logstash/:/opt/
      - ./conf/logstash/:/usr/share/logstash/pipeline/
    ports:
      - "5044:5044"
      - "9600:9600"
    dns:
      - 8.8.8.8
      - 8.8.4.4
  
  